feat: set impl on test-snappyenv
Signed-off-by: Lincoln Wallace <lincoln.wallace@canonical.com>

diff --git a/tests/initialize b/tests/initialize
--- a/tests/initialize
+++ b/tests/initialize
@@ -144,6 +144,13 @@ init_tests() {
   fi
 }
 
+check_impl() {
+  if [[ "$impl" != "bash" && "$impl" != "rust" ]]; then
+    echo "Error: --impl/-i must be either 'bash' or 'rust'" >&2
+    help
+  fi
+}
+
 SNAP=envtester
 SNAP_COMMON=/var/snap/"${SNAP}"/common/
 impl=""
@@ -169,9 +176,6 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-if [[ "$impl" != "bash" && "$impl" != "rust" ]]; then
-  echo "Error: --impl/-i must be either 'bash' or 'rust'" >&2
-  help
-fi
+check_impl
 
 inject_test_app "$impl"
