feat: address reviews
Signed-off-by: Lincoln Wallace <lincoln.wallace@canonical.com>

diff --git a/tests/test-snappyenv b/tests/test-snappyenv
--- a/tests/test-snappyenv
+++ b/tests/test-snappyenv
@@ -2,30 +2,54 @@
 
 set -eu
 
-BASEDIR=$(dirname "$(realpath "$0")")
+check_syntax() {
+  local snap_app="$1"
+  local env_value="$2"
+  if eval "$snap_app" | grep -q "^${env_value}="; then
+    echo -e "\n[ERROR] Value '$env_name' SHOULD NOT BE set.\n"
+    return 1
+  fi
+  return 0
+}
 
-PROJECT_ROOT="$BASEDIR/.."
+check_env_exist() {
+  local snap_app="$1"
+  local env_name="$2"
 
-assert_env() {
+  if ! eval "$snap_app" | grep -q "^${env_name}="; then
+    echo -e "\n[ERROR] Environment variable '$env_name' is not set, for the app: $snap_app.\n"
+    return 1
+  fi
+}
+
+check_env_not_exist() {
+
+  local snap_app="$1"
+  local env_name="$2"
+
+  if eval "$snap_app" | grep -q "^${env_name}="; then
+    echo -e "\n[ERROR] Environment variable '$env_name' SHOULD NOT be set, for the app: $snap_app.\n"
+    return 1
+  fi
+}
+
+check_env_value() {
   local snap_app="$1"
   local env_name="$2"
   local exp_value="$3"
   local actual_value
-  if ! eval "$snap_app" | grep -q "^${env_name}="; then
-    echo -e "\n[WARN] Environment variable '$env_name' is not set.\n"
-    return 1
-  fi
+
   if [ -z "$env_name" ]; then
+    echo -e "\n\nHERE HERE\n\n "
     empty=$("$snap_app" | grep "=${exp_value}")
     [ -z "$empty" ] || return 1
   fi
   actual_value=$("$snap_app" | grep "^${env_name}=" | cut -d'=' -f2-)
   if [ "$actual_value" != "$exp_value" ]; then
-    echo -e "\n[ERROR] Environment variable '$env_name' does not match the expected value."
+    echo -e "\n[ERROR] Environment variable '$env_name' does not match the expected value, for the app: $snap_app"
     echo -e "[ERROR] Expected: '$env_name=$exp_value', but got: '$env_name=$actual_value'\n"
     return 1
   fi
-  return 0
 }
 
 check_root() {
@@ -35,30 +59,35 @@ check_root() {
   fi
 }
 
-teardown() {
-  echo "Cleaning and exit..."
+clean() {
+  echo "Cleaning..."
   snap remove --purge "${SNAP}"
   git restore snap/snapcraft.yaml
+  sudo chown $SUDO_USER:$SUDO_USER snap/snapcraft.yaml
 
   rm -rf squashfs-root
 }
 
 fail() {
-  teardown
+  clean
   exit 1
 }
 
-check_root
+BASEDIR=$(dirname "$(realpath "$0")")
+PROJECT_ROOT="$BASEDIR/.."
 
 SNAP=envtester
+SNAP_COMMON=/var/snap/"${SNAP}"/common/
+
+check_root
+clean
 
 echo "SNAP NAME: ${SNAP}"
 
 pushd "$PROJECT_ROOT" || exit 1
 
 # 'sudo -u "$RUN_AS"' prevents a permission denied error when using yq as snap.
-RUN_AS="${SUDO_USER:-$LOGNAME}"
-sudo -u "$RUN_AS" yq '.apps.app-rust-2 = {
+sudo -u "$SUDO_USER" yq '.apps.app-rust-2 = {
   "environment": {
     "env_alias": "app-rust-2"
   },
@@ -70,7 +99,7 @@ sudo -u "$RUN_AS" yq '.apps.app-rust-2 = {
 
 snapcraft -o "${SNAP}".snap
 
-unsquashfs -f "$PROJECT_ROOT/${SNAP}.snap"
+unsquashfs "${PROJECT_ROOT}/${SNAP}.snap"
 
 echo "Check that the env-exporter program is present"
 [ -f squashfs-root/bin/env-exporter ] || fail
@@ -81,26 +110,32 @@ echo "Check that the exec-env script is present"
 snap install "${SNAP}".snap --dangerous
 
 echo -e "\n[envtester] Creating global envfile"
-echo 'HELLO_WORLD="Hello World"' >>/var/snap/"${SNAP}"/common/global.env
+echo 'HELLO_WORLD="Hello World"' >>"$SNAP_COMMON"/global.env
 
 echo "Load global envfile"
-snap set "${SNAP}" envfile=/var/snap/"${SNAP}"/common/global.env
+snap set "${SNAP}" envfile="$SNAP_COMMON"/global.env
 
 echo "[TEST] - Check if the global envfile is loaded the app using Rust snappy-env programs"
-assert_env "${SNAP}.app-rust" "HELLO_WORLD" "Hello World" || fail
-assert_env "${SNAP}.app-rust-2" "HELLO_WORLD" "Hello World" || fail
+check_env_exist "${SNAP}.app-rust" "HELLO_WORLD" || fail
+check_env_value "${SNAP}.app-rust" "HELLO_WORLD" "Hello World" || fail
+
+check_env_exist "${SNAP}.app-rust-2" "HELLO_WORLD" || fail
+check_env_value "${SNAP}.app-rust-2" "HELLO_WORLD" "Hello World" || fail
 
 echo -e "\n[envtester] Creating app-specific envfile"
-echo 'SCOPED=RustVersion' >>/var/snap/"${SNAP}"/common/rust.env
-echo 'SCOPED=Rust2Version' >>/var/snap/"${SNAP}"/common/rust-2.env
+echo 'SCOPED=RustVersion' >>"$SNAP_COMMON"/rust.env
+echo 'SCOPED=Rust2Version' >>"$SNAP_COMMON"/rust-2.env
 
 echo "Load app-specific envfile"
-snap set "${SNAP}" apps.app-rust.envfile=/var/snap/"${SNAP}"/common/rust.env
-snap set "${SNAP}" apps.app-rust-2.envfile=/var/snap/"${SNAP}"/common/rust-2.env
+snap set "${SNAP}" apps.app-rust.envfile="$SNAP_COMMON"/rust.env
+snap set "${SNAP}" apps.app-rust-2.envfile="$SNAP_COMMON"/rust-2.env
 
 echo "[TEST] - Check if the app-specific envfile is loaded for the apps"
-assert_env "${SNAP}.app-rust" "SCOPED" "RustVersion" || fail
-assert_env "${SNAP}.app-rust-2" "SCOPED" "Rust2Version" || fail
+check_env_exist "${SNAP}.app-rust" "SCOPED" || fail
+check_env_value "${SNAP}.app-rust" "SCOPED" "RustVersion" || fail
+
+check_env_exist "${SNAP}.app-rust-2" "SCOPED" || fail
+check_env_value "${SNAP}.app-rust-2" "SCOPED" "Rust2Version" || fail
 
 echo -e "\n[envtester] Setting global env variable"
 
@@ -108,8 +143,11 @@ echo "Set env vars: Global"
 snap set "${SNAP}" env.global="World"
 
 echo "[TEST] - Check if the global env var is set for all apps"
-assert_env "${SNAP}.app-rust" "GLOBAL" "World" || fail
-assert_env "${SNAP}.app-rust-2" "GLOBAL" "World" || fail
+check_env_exist "${SNAP}.app-rust" "GLOBAL" || fail
+check_env_value "${SNAP}.app-rust" "GLOBAL" "World" || fail
+
+check_env_exist "${SNAP}.app-rust-2" "GLOBAL" || fail
+check_env_value "${SNAP}.app-rust-2" "GLOBAL" "World" || fail
 
 echo -e "\n[envtester] Setting app-specific env variable"
 echo "Set env vars: specific to each app"
@@ -117,29 +155,33 @@ snap set "${SNAP}" apps.app-rust.env.hello="Hello"
 snap set "${SNAP}" apps.app-rust-2.env.specific="City"
 
 echo "[TEST] - Check if the app-specific env var IS SET for the app 'app-rust'"
-assert_env "${SNAP}.app-rust" "HELLO" "Hello" || fail
+check_env_exist "${SNAP}.app-rust" "HELLO" || fail
+check_env_value "${SNAP}.app-rust" "HELLO" "Hello" || fail
 
-echo -e "\n[TEST] [WARN EXPECTED] - Check if the app-specific env var IS NOT SET for the app 'app-rust-2'"
-! assert_env "${SNAP}.app-rust-2" "HELLO" "Hello" || fail
+echo -e "\n[TEST] - Check if the app-specific env var IS NOT SET for the app 'app-rust-2'"
+check_env_not_exist "${SNAP}.app-rust-2" "HELLO" || fail
 
 echo -e "\n[TEST] - Check if the app-specific env var IS SET for the app 'app-rust-2'"
-assert_env "${SNAP}.app-rust-2" "SPECIFIC" "City" || fail
+check_env_exist "${SNAP}.app-rust-2" "SPECIFIC" || fail
+check_env_value "${SNAP}.app-rust-2" "SPECIFIC" "City" || fail
 
-echo -e "\n[TEST] [WARN EXPECTED] - Check if the app-specific env var IS NOT SET for the app 'app-rust'"
-! assert_env "${SNAP}.app-rust" "SPECIFIC" "City" || fail
+echo -e "\n[TEST] - Check if the app-specific env var IS NOT SET for the app 'app-rust'"
+check_env_not_exist "${SNAP}.app-rust" "SPECIFIC" || fail
 
 echo -e "\n[envtester] Testing options syntax"
 snap set "${SNAP}" env.word.dot="wrong"
-echo "[TEST] [WARN EXPECTED] - Check if the key with dot was ignored"
-! assert_env "${SNAP}.app-rust" "" "wrong" || fail
+echo "[TEST] - Check if the key with dot was ignored"
+check_syntax "${SNAP}.app-rust" "wrong" || fail
 
 echo -e "\n[envtester] Testing order of env vars"
-echo 'ORDER="From envfile"' >>/var/snap/"${SNAP}"/common/local.env
+echo 'ORDER="From envfile"' >>"$SNAP_COMMON"/local.env
 snap set "${SNAP}" apps.app-rust.env.order="from app-specific"
-snap set "${SNAP}" apps.app-rust.envfile=/var/snap/"${SNAP}"/common/local.env
-echo "[TEST] - Check if local overrites global"
-assert_env "${SNAP}.app-rust" "ORDER" "from app-specific" || fail
+snap set "${SNAP}" apps.app-rust.envfile="$SNAP_COMMON"/local.env
+echo "[TEST] - Check if local overrides global"
 
-teardown
+check_env_exist "${SNAP}.app-rust" "ORDER" || fail
+check_env_value "${SNAP}.app-rust" "ORDER" "from app-specific" || fail
+
+clean
 popd || exit 1
 exit 0
